name: Room Assistant Trilatetration
version: '1.0.6'
slug: room-assistant-trilatetration
description: "Calculate the location of room-assistant devices inside the house"
startup: services
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
hassio_api: true
homeassistant_api: true
host_network: true
map:
  - config:rw
options:
  location_mappings: null
  home_dimensions: null
  room_assistant_url: null
  update_interval: 5
schema:
  update_interval: int
  room_assistant_url: str
  location_mappings:
    - name: str
      x: float
      y: float
  home_dimensions:
    width: float
    height: float
