name: Room Assistant Trilatetration
version: '1.0'
slug: room-assistant-trilatetration
description: "Calculate the location of room-assistant devices inside the house"
startup: services
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
hassio_api: true
homeassistant_api: true
host_network: true
map:
  - config:rw
options:
  ha_long_lived_token: null
  location_mappings: null
  update_interval: 5
schema:
  ha_long_lived_token: str
  update_interval: int
  location_mappings:
    - x: float
      y: float
